export default {
    active: 'Active',
    add: 'Add',
    cancel: 'Cancel',
    commaSeparatedValues: 'Comma Separated Values',
    course: 'Course',
    delete: 'Delete',
    deleteOrganization: 'Are you sure you want to delete this Organization?',
    deleteOrgDoubleCheck: 'Are you really sure? This may confuse any instructor or student who want to see related information.',
    deleteCourse: 'Are you sure you want to delete this Course?',
    deleteCourseDoubleCheck: 'Are you really sure? This may corrupt the system and affect existing course sections.',
    deleteSemester: 'Are you sure you want to delete this Semester?',
    deleteSemDoubleCheck: 'Are you really sure? This may corrupt the system and affect existing semesters.',
    edit: 'Edit',
    editCourse: 'Edit Course',
    editOrganization: 'Edit Organization',
    editSection: 'Edit Section',
    editSemester: 'Edit Semester',
    email: 'Email',
    endDate: 'End Date',
    firstName: 'First Name',
    identifier: 'Identifier',
    inactive: 'Inactive',
    instructor: 'Instructor',
    instructors: 'Instructors',
    lastName: 'Last Name',
    logo: 'Logo',
    name: 'Name',
    new: 'New',
    newCourse: 'New Course',
    newOrganization: 'New Organization',
    newSection: 'New Section',
    newSemester: 'New Semester',
    newSemesterName:"Name (include year)",
    newSemesterToolTip:"The semester name will be displayed distinguish sections with the same identifier.  We recommend including the year in the semester name to distinguish semesters with the same name.    Each semester is only used by one organization.",
    number: 'Number',
    observer: 'Observer',
    observers: 'Observers',
    observerToolTip:"Observers are not currently implemented",
    organization: 'Organization',
    save: 'Save',
    section: 'Section',
    semester: 'Semester',
    singleEntryForm: 'Single Entry Form',
    startDate: 'Start Date',
    status: 'Status',
    student: 'Student',
    students: 'Students',
    addStudents: 'Add Students',
    addStudent: 'Add Student',
    upload: 'Drag an image or click',
    volunteer: 'Volunteer',
    yes: 'Yes',
    no: 'No',
    Approved: 'Approved',
    Pending:'Pending',
    Inactive: 'Inactive',
    csvHeaders1: 'Email, First Name, Last Name, Active, Volunteer',
    csvHeaders2: 'Email, Last Name, First Name, Active, Volunteer',
    csvHeaders3: 'First Name, Last Name, Email, Active, Volunteer',
    csvHeaders4: 'Last Name, First Name, Email, Active, Volunteer',
    csvHeaders5: 'First Name, Email, Last Name, Active, Volunteer',
    csvHeaders6: 'Last Name, Email, First Name, Active, Volunteer'
};