export default {
    account: 'Account',
    name: 'Name',
    firstName: 'Preferred First Name',
    lastName: 'Preferred Last Name',
    officialFirstName: 'Official First Name',
    officialLastName: 'Official Last Name',
    email: 'Email',
    password: 'Password',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    profilePicture: 'Profile Picture',
    upload: 'Drag an image or click',
    edit: 'Edit',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    editAccount: 'Edit My Profile',
    loginEmail: 'Login Email',
    notificationEmail: 'Notification Email',
    phoneNumber: 'Text Number',
    alias: 'Alias',
    aliasTooltip: 'Alternative name',
    avatar: 'Avatar',
    yes: 'Yes',
    no: 'No',
    admin: 'System-wide Role: Administrator',
    instructor: 'System-wide Role: Instructor',
    Bad: 'Bad',
    NotGood: 'Not good',
    Decent: 'Decent',
    Strong: 'Strong',
    Great: 'Great',
    accountEmailTooltip: 'Test tooltip for email',
    timezone: 'Time Zone'
}